---
- name: generate kubernetes manifests
  sudo: yes
  template:
    src: "{{ item }}.yml"
    dest: "{{ kube_manifest_dir }}/{{ item }}.yml"
    owner: root
    group: root
    mode: 0644
  with_items:
    - kube-proxy
  tags:
    - node
    - kubernetes

- name: generate consul config for NodePort services
  sudo: yes
  template:
    src: nodeport.json.j2
    dest: /etc/consul/nodeport.json
  notify:
    - reload consul
  tags:
    - node
    - kubernetes
